# Generated by Django 5.1.1 on 2024-10-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título da tarefa.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada da tarefa.')),
                ('priority', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], default='Média', help_text='Prioridade da tarefa.', max_length=10)),
                ('category', models.CharField(choices=[('Trabalho', 'Trabalho'), ('Pessoal', 'Pessoal'), ('Outros', 'Outros')], default='Outros', help_text='Categoria da tarefa.', max_length=10)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Progresso', 'Em Progresso'), ('Concluída', 'Concluída'), ('Arquivada', 'Arquivada')], default='Pendente', help_text='Status da tarefa.', max_length=15)),
                ('deadline', models.DateTimeField(help_text='Data limite para conclusão da tarefa.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação da tarefa.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que a tarefa foi atualizada.')),
                ('completed', models.BooleanField(default=False, help_text='Indica se a tarefa foi concluída.')),
                ('comments', models.TextField(blank=True, help_text='Comentários adicionais sobre a tarefa.')),
                ('assigned_to', models.CharField(blank=True, help_text='Responsável pela tarefa.', max_length=100)),
                ('estimated_time_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Tempo estimado para conclusão em horas.', max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['deadline'],
            },
        ),
    ]
